// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Message.proto

package org.txazo.im.common.protocol;

public final class MessageBody {
  private MessageBody() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code protocol.CommandType}
   */
  public enum CommandType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>HeartbeatRequest = 0;</code>
     */
    HeartbeatRequest(0),
    /**
     * <code>HeartbeatResponse = 1;</code>
     */
    HeartbeatResponse(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>HeartbeatRequest = 0;</code>
     */
    public static final int HeartbeatRequest_VALUE = 0;
    /**
     * <code>HeartbeatResponse = 1;</code>
     */
    public static final int HeartbeatResponse_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static CommandType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static CommandType forNumber(int value) {
      switch (value) {
        case 0: return HeartbeatRequest;
        case 1: return HeartbeatResponse;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<CommandType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        CommandType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<CommandType>() {
            public CommandType findValueByNumber(int number) {
              return CommandType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return org.txazo.im.common.protocol.MessageBody.getDescriptor().getEnumTypes().get(0);
    }

    private static final CommandType[] VALUES = values();

    public static CommandType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private CommandType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:protocol.CommandType)
  }

  public interface HeartbeatRequestPacketOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protocol.HeartbeatRequestPacket)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.protocol.CommandType command = 1;</code>
     * @return The enum numeric value on the wire for command.
     */
    int getCommandValue();
    /**
     * <code>.protocol.CommandType command = 1;</code>
     * @return The command.
     */
    org.txazo.im.common.protocol.MessageBody.CommandType getCommand();
  }
  /**
   * Protobuf type {@code protocol.HeartbeatRequestPacket}
   */
  public  static final class HeartbeatRequestPacket extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protocol.HeartbeatRequestPacket)
      HeartbeatRequestPacketOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use HeartbeatRequestPacket.newBuilder() to construct.
    private HeartbeatRequestPacket(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private HeartbeatRequestPacket() {
      command_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new HeartbeatRequestPacket();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private HeartbeatRequestPacket(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              command_ = rawValue;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.txazo.im.common.protocol.MessageBody.internal_static_protocol_HeartbeatRequestPacket_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.txazo.im.common.protocol.MessageBody.internal_static_protocol_HeartbeatRequestPacket_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.txazo.im.common.protocol.MessageBody.HeartbeatRequestPacket.class, org.txazo.im.common.protocol.MessageBody.HeartbeatRequestPacket.Builder.class);
    }

    public static final int COMMAND_FIELD_NUMBER = 1;
    private int command_;
    /**
     * <code>.protocol.CommandType command = 1;</code>
     * @return The enum numeric value on the wire for command.
     */
    public int getCommandValue() {
      return command_;
    }
    /**
     * <code>.protocol.CommandType command = 1;</code>
     * @return The command.
     */
    public org.txazo.im.common.protocol.MessageBody.CommandType getCommand() {
      @SuppressWarnings("deprecation")
      org.txazo.im.common.protocol.MessageBody.CommandType result = org.txazo.im.common.protocol.MessageBody.CommandType.valueOf(command_);
      return result == null ? org.txazo.im.common.protocol.MessageBody.CommandType.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (command_ != org.txazo.im.common.protocol.MessageBody.CommandType.HeartbeatRequest.getNumber()) {
        output.writeEnum(1, command_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (command_ != org.txazo.im.common.protocol.MessageBody.CommandType.HeartbeatRequest.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, command_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.txazo.im.common.protocol.MessageBody.HeartbeatRequestPacket)) {
        return super.equals(obj);
      }
      org.txazo.im.common.protocol.MessageBody.HeartbeatRequestPacket other = (org.txazo.im.common.protocol.MessageBody.HeartbeatRequestPacket) obj;

      if (command_ != other.command_) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + COMMAND_FIELD_NUMBER;
      hash = (53 * hash) + command_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.txazo.im.common.protocol.MessageBody.HeartbeatRequestPacket parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.txazo.im.common.protocol.MessageBody.HeartbeatRequestPacket parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.txazo.im.common.protocol.MessageBody.HeartbeatRequestPacket parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.txazo.im.common.protocol.MessageBody.HeartbeatRequestPacket parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.txazo.im.common.protocol.MessageBody.HeartbeatRequestPacket parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.txazo.im.common.protocol.MessageBody.HeartbeatRequestPacket parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.txazo.im.common.protocol.MessageBody.HeartbeatRequestPacket parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.txazo.im.common.protocol.MessageBody.HeartbeatRequestPacket parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.txazo.im.common.protocol.MessageBody.HeartbeatRequestPacket parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.txazo.im.common.protocol.MessageBody.HeartbeatRequestPacket parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.txazo.im.common.protocol.MessageBody.HeartbeatRequestPacket parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.txazo.im.common.protocol.MessageBody.HeartbeatRequestPacket parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.txazo.im.common.protocol.MessageBody.HeartbeatRequestPacket prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protocol.HeartbeatRequestPacket}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protocol.HeartbeatRequestPacket)
        org.txazo.im.common.protocol.MessageBody.HeartbeatRequestPacketOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.txazo.im.common.protocol.MessageBody.internal_static_protocol_HeartbeatRequestPacket_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.txazo.im.common.protocol.MessageBody.internal_static_protocol_HeartbeatRequestPacket_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.txazo.im.common.protocol.MessageBody.HeartbeatRequestPacket.class, org.txazo.im.common.protocol.MessageBody.HeartbeatRequestPacket.Builder.class);
      }

      // Construct using org.txazo.im.common.protocol.MessageBody.HeartbeatRequestPacket.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        command_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.txazo.im.common.protocol.MessageBody.internal_static_protocol_HeartbeatRequestPacket_descriptor;
      }

      @java.lang.Override
      public org.txazo.im.common.protocol.MessageBody.HeartbeatRequestPacket getDefaultInstanceForType() {
        return org.txazo.im.common.protocol.MessageBody.HeartbeatRequestPacket.getDefaultInstance();
      }

      @java.lang.Override
      public org.txazo.im.common.protocol.MessageBody.HeartbeatRequestPacket build() {
        org.txazo.im.common.protocol.MessageBody.HeartbeatRequestPacket result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.txazo.im.common.protocol.MessageBody.HeartbeatRequestPacket buildPartial() {
        org.txazo.im.common.protocol.MessageBody.HeartbeatRequestPacket result = new org.txazo.im.common.protocol.MessageBody.HeartbeatRequestPacket(this);
        result.command_ = command_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.txazo.im.common.protocol.MessageBody.HeartbeatRequestPacket) {
          return mergeFrom((org.txazo.im.common.protocol.MessageBody.HeartbeatRequestPacket)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.txazo.im.common.protocol.MessageBody.HeartbeatRequestPacket other) {
        if (other == org.txazo.im.common.protocol.MessageBody.HeartbeatRequestPacket.getDefaultInstance()) return this;
        if (other.command_ != 0) {
          setCommandValue(other.getCommandValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.txazo.im.common.protocol.MessageBody.HeartbeatRequestPacket parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.txazo.im.common.protocol.MessageBody.HeartbeatRequestPacket) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int command_ = 0;
      /**
       * <code>.protocol.CommandType command = 1;</code>
       * @return The enum numeric value on the wire for command.
       */
      public int getCommandValue() {
        return command_;
      }
      /**
       * <code>.protocol.CommandType command = 1;</code>
       * @param value The enum numeric value on the wire for command to set.
       * @return This builder for chaining.
       */
      public Builder setCommandValue(int value) {
        command_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.protocol.CommandType command = 1;</code>
       * @return The command.
       */
      public org.txazo.im.common.protocol.MessageBody.CommandType getCommand() {
        @SuppressWarnings("deprecation")
        org.txazo.im.common.protocol.MessageBody.CommandType result = org.txazo.im.common.protocol.MessageBody.CommandType.valueOf(command_);
        return result == null ? org.txazo.im.common.protocol.MessageBody.CommandType.UNRECOGNIZED : result;
      }
      /**
       * <code>.protocol.CommandType command = 1;</code>
       * @param value The command to set.
       * @return This builder for chaining.
       */
      public Builder setCommand(org.txazo.im.common.protocol.MessageBody.CommandType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        command_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.protocol.CommandType command = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearCommand() {
        
        command_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protocol.HeartbeatRequestPacket)
    }

    // @@protoc_insertion_point(class_scope:protocol.HeartbeatRequestPacket)
    private static final org.txazo.im.common.protocol.MessageBody.HeartbeatRequestPacket DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.txazo.im.common.protocol.MessageBody.HeartbeatRequestPacket();
    }

    public static org.txazo.im.common.protocol.MessageBody.HeartbeatRequestPacket getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<HeartbeatRequestPacket>
        PARSER = new com.google.protobuf.AbstractParser<HeartbeatRequestPacket>() {
      @java.lang.Override
      public HeartbeatRequestPacket parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new HeartbeatRequestPacket(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<HeartbeatRequestPacket> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<HeartbeatRequestPacket> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.txazo.im.common.protocol.MessageBody.HeartbeatRequestPacket getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface HeartbeatResponsePacketOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protocol.HeartbeatResponsePacket)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.protocol.CommandType command = 1;</code>
     * @return The enum numeric value on the wire for command.
     */
    int getCommandValue();
    /**
     * <code>.protocol.CommandType command = 1;</code>
     * @return The command.
     */
    org.txazo.im.common.protocol.MessageBody.CommandType getCommand();
  }
  /**
   * Protobuf type {@code protocol.HeartbeatResponsePacket}
   */
  public  static final class HeartbeatResponsePacket extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protocol.HeartbeatResponsePacket)
      HeartbeatResponsePacketOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use HeartbeatResponsePacket.newBuilder() to construct.
    private HeartbeatResponsePacket(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private HeartbeatResponsePacket() {
      command_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new HeartbeatResponsePacket();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private HeartbeatResponsePacket(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              command_ = rawValue;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.txazo.im.common.protocol.MessageBody.internal_static_protocol_HeartbeatResponsePacket_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.txazo.im.common.protocol.MessageBody.internal_static_protocol_HeartbeatResponsePacket_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.txazo.im.common.protocol.MessageBody.HeartbeatResponsePacket.class, org.txazo.im.common.protocol.MessageBody.HeartbeatResponsePacket.Builder.class);
    }

    public static final int COMMAND_FIELD_NUMBER = 1;
    private int command_;
    /**
     * <code>.protocol.CommandType command = 1;</code>
     * @return The enum numeric value on the wire for command.
     */
    public int getCommandValue() {
      return command_;
    }
    /**
     * <code>.protocol.CommandType command = 1;</code>
     * @return The command.
     */
    public org.txazo.im.common.protocol.MessageBody.CommandType getCommand() {
      @SuppressWarnings("deprecation")
      org.txazo.im.common.protocol.MessageBody.CommandType result = org.txazo.im.common.protocol.MessageBody.CommandType.valueOf(command_);
      return result == null ? org.txazo.im.common.protocol.MessageBody.CommandType.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (command_ != org.txazo.im.common.protocol.MessageBody.CommandType.HeartbeatRequest.getNumber()) {
        output.writeEnum(1, command_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (command_ != org.txazo.im.common.protocol.MessageBody.CommandType.HeartbeatRequest.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, command_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.txazo.im.common.protocol.MessageBody.HeartbeatResponsePacket)) {
        return super.equals(obj);
      }
      org.txazo.im.common.protocol.MessageBody.HeartbeatResponsePacket other = (org.txazo.im.common.protocol.MessageBody.HeartbeatResponsePacket) obj;

      if (command_ != other.command_) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + COMMAND_FIELD_NUMBER;
      hash = (53 * hash) + command_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.txazo.im.common.protocol.MessageBody.HeartbeatResponsePacket parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.txazo.im.common.protocol.MessageBody.HeartbeatResponsePacket parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.txazo.im.common.protocol.MessageBody.HeartbeatResponsePacket parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.txazo.im.common.protocol.MessageBody.HeartbeatResponsePacket parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.txazo.im.common.protocol.MessageBody.HeartbeatResponsePacket parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.txazo.im.common.protocol.MessageBody.HeartbeatResponsePacket parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.txazo.im.common.protocol.MessageBody.HeartbeatResponsePacket parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.txazo.im.common.protocol.MessageBody.HeartbeatResponsePacket parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.txazo.im.common.protocol.MessageBody.HeartbeatResponsePacket parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.txazo.im.common.protocol.MessageBody.HeartbeatResponsePacket parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.txazo.im.common.protocol.MessageBody.HeartbeatResponsePacket parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.txazo.im.common.protocol.MessageBody.HeartbeatResponsePacket parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.txazo.im.common.protocol.MessageBody.HeartbeatResponsePacket prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protocol.HeartbeatResponsePacket}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protocol.HeartbeatResponsePacket)
        org.txazo.im.common.protocol.MessageBody.HeartbeatResponsePacketOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.txazo.im.common.protocol.MessageBody.internal_static_protocol_HeartbeatResponsePacket_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.txazo.im.common.protocol.MessageBody.internal_static_protocol_HeartbeatResponsePacket_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.txazo.im.common.protocol.MessageBody.HeartbeatResponsePacket.class, org.txazo.im.common.protocol.MessageBody.HeartbeatResponsePacket.Builder.class);
      }

      // Construct using org.txazo.im.common.protocol.MessageBody.HeartbeatResponsePacket.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        command_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.txazo.im.common.protocol.MessageBody.internal_static_protocol_HeartbeatResponsePacket_descriptor;
      }

      @java.lang.Override
      public org.txazo.im.common.protocol.MessageBody.HeartbeatResponsePacket getDefaultInstanceForType() {
        return org.txazo.im.common.protocol.MessageBody.HeartbeatResponsePacket.getDefaultInstance();
      }

      @java.lang.Override
      public org.txazo.im.common.protocol.MessageBody.HeartbeatResponsePacket build() {
        org.txazo.im.common.protocol.MessageBody.HeartbeatResponsePacket result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.txazo.im.common.protocol.MessageBody.HeartbeatResponsePacket buildPartial() {
        org.txazo.im.common.protocol.MessageBody.HeartbeatResponsePacket result = new org.txazo.im.common.protocol.MessageBody.HeartbeatResponsePacket(this);
        result.command_ = command_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.txazo.im.common.protocol.MessageBody.HeartbeatResponsePacket) {
          return mergeFrom((org.txazo.im.common.protocol.MessageBody.HeartbeatResponsePacket)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.txazo.im.common.protocol.MessageBody.HeartbeatResponsePacket other) {
        if (other == org.txazo.im.common.protocol.MessageBody.HeartbeatResponsePacket.getDefaultInstance()) return this;
        if (other.command_ != 0) {
          setCommandValue(other.getCommandValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.txazo.im.common.protocol.MessageBody.HeartbeatResponsePacket parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.txazo.im.common.protocol.MessageBody.HeartbeatResponsePacket) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int command_ = 0;
      /**
       * <code>.protocol.CommandType command = 1;</code>
       * @return The enum numeric value on the wire for command.
       */
      public int getCommandValue() {
        return command_;
      }
      /**
       * <code>.protocol.CommandType command = 1;</code>
       * @param value The enum numeric value on the wire for command to set.
       * @return This builder for chaining.
       */
      public Builder setCommandValue(int value) {
        command_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.protocol.CommandType command = 1;</code>
       * @return The command.
       */
      public org.txazo.im.common.protocol.MessageBody.CommandType getCommand() {
        @SuppressWarnings("deprecation")
        org.txazo.im.common.protocol.MessageBody.CommandType result = org.txazo.im.common.protocol.MessageBody.CommandType.valueOf(command_);
        return result == null ? org.txazo.im.common.protocol.MessageBody.CommandType.UNRECOGNIZED : result;
      }
      /**
       * <code>.protocol.CommandType command = 1;</code>
       * @param value The command to set.
       * @return This builder for chaining.
       */
      public Builder setCommand(org.txazo.im.common.protocol.MessageBody.CommandType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        command_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.protocol.CommandType command = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearCommand() {
        
        command_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protocol.HeartbeatResponsePacket)
    }

    // @@protoc_insertion_point(class_scope:protocol.HeartbeatResponsePacket)
    private static final org.txazo.im.common.protocol.MessageBody.HeartbeatResponsePacket DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.txazo.im.common.protocol.MessageBody.HeartbeatResponsePacket();
    }

    public static org.txazo.im.common.protocol.MessageBody.HeartbeatResponsePacket getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<HeartbeatResponsePacket>
        PARSER = new com.google.protobuf.AbstractParser<HeartbeatResponsePacket>() {
      @java.lang.Override
      public HeartbeatResponsePacket parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new HeartbeatResponsePacket(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<HeartbeatResponsePacket> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<HeartbeatResponsePacket> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.txazo.im.common.protocol.MessageBody.HeartbeatResponsePacket getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_HeartbeatRequestPacket_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_HeartbeatRequestPacket_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_HeartbeatResponsePacket_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_HeartbeatResponsePacket_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rMessage.proto\022\010protocol\"@\n\026HeartbeatRe" +
      "questPacket\022&\n\007command\030\001 \001(\0162\025.protocol." +
      "CommandType\"A\n\027HeartbeatResponsePacket\022&" +
      "\n\007command\030\001 \001(\0162\025.protocol.CommandType*:" +
      "\n\013CommandType\022\024\n\020HeartbeatRequest\020\000\022\025\n\021H" +
      "eartbeatResponse\020\001B+\n\034org.txazo.im.commo" +
      "n.protocolB\013MessageBodyb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_protocol_HeartbeatRequestPacket_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protocol_HeartbeatRequestPacket_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_HeartbeatRequestPacket_descriptor,
        new java.lang.String[] { "Command", });
    internal_static_protocol_HeartbeatResponsePacket_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_protocol_HeartbeatResponsePacket_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_HeartbeatResponsePacket_descriptor,
        new java.lang.String[] { "Command", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
